apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  #nodeSelector:
    #node.kubernetes.io/instance-type: "m5.xlarge"
  containers:
  - name: pod
    image: morosow/nvtop
    command: ["/bin/sh"]
    args: ["-c", "while true; do date; sleep 10; done"]
    resources:
      limits:
        nvidia.com/gpu: 4
        vpc.amazonaws.com/efa: 4
      requests:
        nvidia.com/gpu: 4
        vpc.amazonaws.com/efa: 4

